language: go

go:
  - "1.14"

addons:
  sonarcloud:
    organization: "schnatterer-github"

script:
  -  docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.24.0 golangci-lint run --out-format checkstyle ./... > report.xml  || true
  # Execute tests and coverage
  - go test ./... -json > report.json
  - go test ./... -coverprofile=coverage.out
  # SonarCloud analysis will run its own code analysis, and also reuse the linters' results
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'